[package]
name = "miocp"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
pin-project = "1.0.7"
parking_lot = "0.11.1"

[dependencies.winapi]
version = "0.3.9"
features = [
    "winnt",
    "handleapi",
    "ioapiset",
    "minwinbase",
    "winerror"
]

[dev-dependencies]
tokio = {version = "1.0", features = ["full"]}
