[package]
name = "iocp-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
publish = false

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
